### ISSUE TITLE
Need a new "dessicated" graphic for Giant Boar PawnKindDef

### ISSUE THREAD

**Issue by edbmods** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Dwarves#18]
The Giant Boar pawn kinds reference a `CritterDessicatedMedium` texture that is no longer in the vanilla game for the 1.0 release.  This results in the purple/pink missing texture graphic when the animal rots to a skeleton.

```
        <dessicatedBodyGraphicData>
          <texPath>Things/Pawn/Animal/Dessicated/CritterDessicatedMedium</texPath>
          <drawSize>2.3</drawSize>
        </dessicatedBodyGraphicData>
```
Looks like some animals in the other Lord of the Rims mods do the same.

**Comment by jecrell** [comment]
Fixed
