### ISSUE TITLE
Dwarves (and hobbits) generating naked and/or headless

### ISSUE THREAD

**Issue by clcrawford** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Dwarves#23]
On B19,

Every time I try to start a new game, if I go with the dwarven settlement scenario, some dwarves generate fine, with clothing, and others will have no clothing, AND no heads. If I try any of the Third Age scenarios, dwarves and hobbits are both naked (but with their heads still attached). I've updated and adjusted mod order but the issue is persisting. Same thing happens with the hobbits, but elves are unaffected by this issue. 

Here's the error log I'm getting during generation of a game: 
https://git.io/fAUQ0

**Comment by jecrell** [comment]
This issue has been fixed around a week ago. I hope you enjoy your dwarves now that they've got their heads on straight!
