### ISSUE TITLE
Plants grow at half speed with this mod enabled

### ISSUE THREAD

**Issue by Cobutt** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Dwarves#6]
Corn grows at 100% on a 200% fertility tile, wild oak trees grow at 50% on normal dirt, etc. I've tried using only the required mods and this one to confirm

**Comment by PhilM-47** [comment]
Thank you, this explains why all my crops seemed to be crawling the past few seasons. I believe the problem may be here in Lord-of-the-Rims---Dwarves/Source/Dwarves/HarmonyPatches.cs:

```
        //Reduces growth rate to one fourth
        public static void get_GrowthRate_PostFix(Plant __instance, ref float __result)
        {
            if (__instance.Map.glowGrid.GameGlowAt(__instance.Position, true) > 0f)
            {
                __result *= 0.5f;
            }
        }
```

There's a field in the new plant defs for underground plants called growOptimalGlow, but this section of code doesn't appear to test for the field and just applies it across all plants, regardless of light level.

**Comment by jecrell** [comment]
Implementing the fix now.
